# Generated by Django 3.2.6 on 2021-09-14 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
