# Generated by Django 3.2.6 on 2021-09-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(blank=True, default='defaults/blog_default.png', upload_to='blogs'),
        ),
    ]
