# Generated by Django 3.2.6 on 2021-09-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blog_blog_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='theme',
            new_name='category',
        ),
    ]
